### ISSUE TITLE
Volume?

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#10]
Hello,

I was wondering if there was any way to control the volume of the playback at all besides through the Unity Audio Source and the microphone. It seems to be consistently a bit low although all the volumes are at a maximum (Oculus Rift Microphone and Audio Source as well). 

Thanks in advance!

**Comment by martindevans** [comment]
Currently there isn't a built in way to control the amplitude. You could try routing the voice audio to a different audio bus, and then increasing the gain of that bus. You could also try "ducking" all other game audio, which means you don't need the voice to be so loud in the first place. There's a general tutorial on audio mixing for voice I wrote [here](https://dissonance.readthedocs.io/en/latest/Tutorials/Audio-Mixing/).

In addition to this there are two features we could add to Dissonance:
 - We have plans to add per channel volume, this would allow you to set the relative volume of different channels (probably not what you need here since this only *reduces* the volume of a particular channel relative to all others).
 - Currently all microphone input is sent through a preprocessor which does (amongst other things) **automatic gain control** - this attempts to keep all voice input at approximately the same level. I will experiment with exposing control of this target level for the next version. In the meantime if you'd like experiment with these settings for yourself:

```
//MicrophoneCapture.cs Line 82
_speex = new SpeexDspNative.Preprocessor(frameSize, _format.SampleRate, 0) {
    AutomaticGainControl = true,
    Denoise = true

    //You could experiment with these settings:
    AutomaticGainControlLevel = ???,        //Value between 1 and 32768
    AutomaticGainControlLevelMax = ???  // Max AGC gain (dB)
};
```

**Comment by citron4000** [comment]
Thanks a lot for the reply. We'll try on our side with the audio mixer and the automatic gain control value.

**Comment by martindevans** [comment]
I've been experimenting with exposing the preprocessor controls to the user (nearly done. I might get a release including it out tomorrow, but no promises). While doing this I discovered that my earlier suggestion regarding the preprocessor wouldn't work (AGC preprocessing was not applied in certain circumstances). I'm afraid you'll have to wait until I get out the next release which will fix the bug.

Fiddling with the audio mixer will work, of course!

**Comment by citron4000** [comment]
Hello,

Currently we are using an AudioMixer to increase the voice's volume and make some other changes to other groups.

In the last versions, since the AudioSource is added in the code by the `DissonanceComms` class, I can't just add the Mixer in the AudioSource. I had to do it in the code in the `CreatePlayerback` method. Something like this:

```
AudioMixer mixer = Resources.Load("MyMixer") as AudioMixer;
string outputMixer = "VoiceGroup";
audioSource.outputAudioMixerGroup = mixer.FindMatchingGroups(outputMixer)[0];
```

How would you go about it so we don't need to extend the entire DissonanceComms class?

Thank you!

**Comment by martindevans** [comment]
Hi Citron,

Do you mean you are setting the mixer output in a custom playback prefab, and adjusting that? If so you should still be able to attach an AudioSource (and set it's mixer) just as you used to, Dissonance should find it and use it. The only thing which changed was that Dissonance will attach the necessary components _if they are not already attached_.

For reference, relevant docs (if you haven't already found them):
 - [Custom playback prefab](https://dissonance.readthedocs.io/en/latest/Tutorials/Playback-Prefab/)
 - [General "audio mixing for voice" tips](https://dissonance.readthedocs.io/en/latest/Tutorials/Audio-Mixing/)

**Comment by citron4000** [comment]
Hi Martin,

Yes that would absolutely work.. I should have looked at the code better. Thanks for the help!
