### ISSUE TITLE
[Bug] On Android ARMv7 device, AEC fail to start

### ISSUE THREAD

**Issue by Vuxt4** [Placeholder-Software/Dissonance#110]
## Context
More information might related to this:
https://github.com/Placeholder-Software/Dissonance/issues/80#issuecomment-410576181

This issue first saw on Version 6.2.0, I have upgraded to 6.2.4 and issue still occurs

## Expected Behavior
AEC should start normally when application started

## Actual Behavior
following error occurs when application started:
`08-07 16:51:43.964  4851  4882 E Unity   : Audio effect Dissonance Echo Cancellation could not be found. Check that the project contains the correct native audio plugin libraries and that the importer settings are set up correctly.`

## Steps to Reproduce
1. See the environment setup at:
https://github.com/Placeholder-Software/Dissonance/issues/80#issuecomment-410576181

2. Start the application and sees:
`08-07 16:51:43.964  4851  4882 E Unity   : Audio effect Dissonance Echo Cancellation could not be found. Check that the project contains the correct native audio plugin libraries and that the importer settings are set up correctly.`

## Your Environment
Development environment:
OS: Win10
UnityEditor: 2017.4.8f1
Dissonance Version: 6.2.4

Target Android Device:
CPU: ARMv7

**Comment by martindevans** [comment]
Someone else has contacted me by email with a similar issue. In their case the AEC seems to work perfectly on PC but simply doesn't load on Mobile - do you have the same issue?

**Comment by martindevans** [comment]
I've submitted an issue about this to Unity, I'll post a link to track the progress as soon as I have one.

**Comment by Vuxt4** [comment]
Yeah, PC works fine, I didn't see such error log pops out, and AEC filter is running as it shows on the editor.
I only see the error log appears on my Android/ARMv7 device

**Comment by martindevans** [comment]
As far as I can see the three possible causes for this are:

 - AudioPluginDissonance.so not loading properly (can't be this, see below)
 - Bug in the Unity audio system which finds and loads filters
 - Something wrong in the way the AudioPluginDissonance file tells Unity about the filters it contains. However the code that does this works on desktop (obviously), so it should work on Android too.

Either way, that's something Unity will have to investigate. We'll have to wait and see what they say on that issue - they're usually pretty quick to come back with an initial response.

Why can't it be the first? Normally I would actually assume it's that - it's a fairly common problem for Dissonance users to have (Unity seems to have a lot of issues properly installing native plugins on install). However this can't possibly be that because there are _two_ things in the AudioPluginDissonance file, the preprocessor (which we explicitly invoke from C# code) and the audio filter (which Unity instantiates automagically). If the preprocessor was missing Dissonance would completely crash during the setup stage and nothing would work so we _know_ the file is loaded properly when invoked by Dissonance. Obviously it's just the automagic Unity audio filter loading code which is failing to find the `Dissonance Echo Cancellation` filter for _some reason_.

**Comment by Vuxt4** [comment]
Yeah, I agree with your point, if library can't be found, we should already have problem with C# preprocessor code, so the best guess might just be the case that something wrong with the audio filter...

Is this only happen on 2017.3.x or 2017.4.x ? Have you ever tried other version of Unity ? (ex: 5.6.x or 2018.1.x, 2018.2.x)

**Comment by martindevans** [comment]
Tom previously tested the AEC filter on his Android phone with `5.6`, as far as I know that worked. Someone else has recently reported this same issue to me by email and it does _not_ work for him on `2018.1.1f1`. It's possible this is a regression of some kind in Unity somewhere between `5.6` (where we tested it worked) and `2017.4` (where it does not work for you). Of course it's also possible that it was broken in `5.6` - since this issue doesn't _crash_ the app we could quite easily have missed it.

**Comment by martindevans** [comment]
Unity have reported that they've managed to reproduce the problem, they're sending it to developers for further investigation.

**Comment by abelevtsov** [comment]
Yeah! It's really gone away now!

Thank you for your attention to the problem!

**Comment by martindevans** [comment]
Fantastic, thanks for confirming that it works 👍
