### ISSUE TITLE
 [bug] [help] SCP Secret Laboratory issonance error

### ISSUE THREAD

**Issue by SpicyMeatBallss** [Placeholder-Software/Dissonance#136]
While playing the steam game SCP Secret Laboratory everything I say sounds dep an warped to other players hearing it trough the in game voice chat, I looke trough the log and found these lines that told me to come here
 
(Filename: Line: 0)

[Dissonance:Playback] (20:42:45.663) EncodedAudioBuffer: Error: Encoded audio heap is getting very large (41 items)! This is probably a bug in Dissonance, we're sorry! Please report the bug on the issue tracker "https://github.com/Placeholder-Software/Dissonance/issues". You could also seek help on the community at "http://placeholder-software.co.uk/dissonance/community" to get help for a temporary workaround. Error ID: 59EE0102-FF75-467A-A50D-00BF670E9B8C
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

[Dissonance:Playback] (20:42:45.663) EncodedAudioBuffer: Error: Encoded audio heap is getting very large (42 items)! This is probably a bug in Dissonance, we're sorry! Please report the bug on the issue tracker "https://github.com/Placeholder-Software/Dissonance/issues". You could also seek help on the community at "http://placeholder-software.co.uk/dissonance/community" to get help for a temporary workaround. Error ID: 59EE0102-FF75-467A-A50D-00BF670E9B8C
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

I am on windows 10 and I do not know how to reproduce or fix the error
I will attach the full log
[output_log.txt](https://github.com/Placeholder-Software/Dissonance/files/2630848/output_log.txt)

**Comment by martindevans** [comment]
Hi, could you contact the game devs about this problem and draw their attention to this issue. Thanks.

The log shows all the signs of very poor performance - perhaps due to a slow or overworked CPU.
 - What hardware are you running this on?
 - How does the game perform (both general overall FPS, or perhaps occasional bad FPS spikes)?
 - Does Task Mnager show one/several cores close to fully loaded (100%)?

**For the SCP devs:** This is probably related to other things going on in the game which are starving Dissonance of sufficient time to do it's work. We added some extra log details to help diagnose performance issues in the last version (in response to the last time one of your gamers encountered similar issues :) ) , so hopefully you can upgrade to the latest version of Dissonance and see if it gives some hints in the log.

**Comment by SpicyMeatBallss** [comment]
About reporting it i had done that before even posting this thread and i have been told the roadmap of future changes has been edited accordingly
The hardware is a bit hard to say but YES my graphic card is not tecnically supported by the game, yet it runs fine without any stuttering or FPS issues, yes it gets close or even at 100% in task manager but that s almost with every game i play and there is no lag ir framedrop

**Comment by martindevans** [comment]
Thanks for the info. We'll wait and see what the SCP devs say when they comment here :)

**Comment by SpicyMeatBallss** [comment]
Can you give a quick look at the modified comment?Also thanks for the help

Il giorno Gio 29 Nov 2018 23:31 Martin Evans <notifications@github.com> ha
scritto:

**Comment by martindevans** [comment]
> Also do you think i can figure out a temporary fix?

I'm afraid not - without the ability to modify the source code there's basically nothing you can do to tweak the behaviour. Sorry :(

**Comment by SpicyMeatBallss** [comment]
Well still thanks a thousand for the help i'll just trust the devs on this, you can change the status of the post to solved or i ll do that myself if i figure out how 
Have a great day

**Comment by martindevans** [comment]
Thanks for the update. I'm glad to hear you managed to work it out :)
