### ISSUE TITLE
Question / feature request: visually display voice level

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#14]
Hello,

It isn't an issue but a question / feature request. Sorry in advance if this is the wrong place to post these, just let me know if there is a more appropriate place for these and I'll post there.

I was wondering if there is a way we can show when someone is talking with Dissonance and also link the 'signal' of this player's talk with a visual cue (for example lips animation or color of a 2D texture turning on and off, etc.). Are there places we can access that within the Audio Playback prefab? Or should we try and use the AudioSource directly?

Thanks in advance!

**Comment by martindevans** [comment]
Hi Citron, it's absolutely fine to post feature requests here :)

> a way we can show when someone is talking with Dissonance

Just getting who is speaking is very simple. Attached to DissonanceComms is a read-only list which contains an object for every player in the session (```VoicePlayerState```). Find the right one and monitor the `IsSpeaking` property.

```
DissonanceComms comms;
var citron = comms.Players.Where(p => p.Name == "citron4000");

//Keep a reference to the citron object, and use the IsSpeaking property to update your UI
ui.isSpeaking = citron.IsSpeaking;
```

> link the 'signal' of this player's talk with a visual cue ... should we try and use the AudioSource directly?

There isn't a built in way to get at the signal of a specific player, so yes you'll have to try and get at the data from the AudioSource for now. This will be a little complex because the AudioSource is meant to be entirely managed by Dissonance. I would suggest creating a custom playback prefab (this is not well documented at the moment, I'll write the docs tomorrow and link them here). Here's a few pointers:

 - The playback prefab *must* have a VoicePlayback behaviour attached to it,
 - You *may* attach an AudioSource (but it's not required, Dissonance will create one automatically if you don't)
 - The following AudioSource settings will be ignored (overwritten by Dissonance):
   - clip
   - loop
   - bypassReverbZones
   - pitch
   - dopplerLevel
   - playOnAwake
 - You can attach whatever additional components you like to the prefab.

You can attach a custom behaviour to the prefab, which monitors the signal:

```
class LevelMonitor
    : MonoBehaviour
{
    VoicePlayback _dissonancePlayback;
    AudioSource _audio;

    void OnEnable()
    {
        _dissonancePlayback = GetComponent<VoicePlayback>();
        _audio = GetComponent<AudioSource>();
    }

   void Update()
   {
        var isSpeaking = dissonancePlayback.IsSpeaking;
        var level = _audio.GetSomeLevelInfo();
        var who = dissonancePlayback.PlayerName;

        //Now post all this information off to your UI to display it
   }
}
```

This is all rather annoying and complex! I'll think about what we could implement to make this easier :)

Incidentally this is actually something we gave some thought to when designing Dissonance - specifically adding a Dissonance integration for [SALSA](https://www.assetstore.unity3d.com/en/#!/content/16944). I looked into it briefly a while a go and I think I concluded that once audio is playing through an AudioSource SALSA will work properly with absolutely no extra work required in Dissonance.

**Comment by martindevans** [comment]
Hi again Citron

The docs I promised for the playback prefab are now available [here](https://dissonance.readthedocs.io/en/latest/Tutorials/Playback-Prefab/).

I have also started some work to make this problem *significantly* easier for you to solve. Hopefully that will be in the next release in a couple of days.

**Comment by citron4000** [comment]
Many thanks Martin! I will start looking in the doc and looking forward to the next release!

**Comment by martindevans** [comment]
Hi Citron

I've just pushed out 0.0.8 with this feature I promised. The [`VoicePlayerState`](https://dissonance.readthedocs.io/en/latest/Reference/Other/VoicePlayerState/) class now has an `Amplitude` property which is a live measure of the signal coming from the player represented by that state. Hopefully the documentation should tell you everything you need to know to take advantage of this, if not tell me what's confusing and I'll update the docs!

**Comment by citron4000** [comment]
Hi Martin,

Great, thanks a lot. If anything, I'll ask here.
