### ISSUE TITLE
[bug] Strange Behaviour on Application Focus/Device Awake (Oculus Go)

### ISSUE THREAD

**Issue by FriskyBishop** [Placeholder-Software/Dissonance#143]
If the device goes to sleep mode (if the user leaves the app running with no input until the Oculus Go goes to sleep) and then wakes the device up, Dissonance starts playing back all the VOIP messages the player missed until it catches up.

For example if the device goes to sleep for 2 minutes and the user awakes the device, dissonance will play back all data from those 2 minutes before playing new messages.

Dissonance HLAPI v6.2.6 (2018-10-31)
Unity 2018.1.6
Device: Oculus Go

## Expected Behavior
Dissonance to ignore all previous data and start playing back from only VOIP messages received after focus.

**Comment by martindevans** [comment]
I think there are two places where this could be happening:

 - The network system could be buffering the packets.
 - Dissonance could be receiving the packets, and buffering them itself.

I assume it must be the first, since while the device is asleep Dissonance is not running.

If you raise the logging settings (Window > Dissonance > Diagnostic) for `Network` and `Playback` to `Debug` do you see any messages about delayed packets? Could you send me (martin@placeholder-software.co.uk) the log?

**Comment by martindevans** [comment]
If you managed to find any more out about this I'll happily re-open the issue :)
