### ISSUE TITLE
endless sceneId assigned to: XXXXXXXXX logs

### ISSUE THREAD

**Issue by FriskyBishop** [Placeholder-Software/Dissonance#153]
Every now and then I get spammed with this messages in the editor (not in play mode), even with an almost totally empty scene (only containing the mirror network manager)
There is no MirrorIgnorance Player Prefab in the scene.

MirrorIgnorance Player Prefab in scene= sceneId assigned to: XXXXXXXXX

It goes on for hundreds of messages - is this a bug?

Unity 2019.1.2

**Comment by martindevans** [comment]
That sounds likely to be a bug in Mirror itself. I'll pass this on to the Mirror devs.

**Comment by vis2k** [comment]
@FriskyBishop can you open a bug report on our Mirror repository and attach the project please?
https://github.com/vis2k/Mirror

**Comment by FriskyBishop** [comment]
@vis2k i did but then i thought it was a dissonance bug so I closed it
https://github.com/vis2k/Mirror/issues/885

**Comment by martindevans** [comment]
I'm assuming it's a bug in Mirror for 2 reasons:
1) That message doesn't come from Dissonance (all Dissonance messages should always be in a format like this: `[Dissonance:loglevel] (HH:mm:ss) classname: message`).
2) If the scene is empty except for the mirror network manager there can't be any Dissonance code running (unless mirror is invoking it).

Of course it is possible that I've set up the Mirror+Dissonance prefabs incorrectly, somehow triggering a problem in Mirror (`MirrorIgnorance Player Prefab` is a prefab which ships with the integration). If that's the case it's still a logging bug in Mirror because of course that message should:
1) State what's wrong
2) Be an be an error message instead of an info message
3) Not be spammed

**Comment by martindevans** [comment]
Did you make any progress on this?

**Comment by FriskyBishop** [comment]
@martindevans the issue mysteriously stopped occurring
