### ISSUE TITLE
[help] namespace name 'Byn' could not be found?

### ISSUE THREAD

**Issue by jamesard** [Placeholder-Software/Dissonance#204]
Hi good folks.
I seem to have an issue (seemingly immediately after importing) that I can't quite figure out on my own.

Starting with a blank project, I import Dissonance, then import an integration...
After importing my integration, the console pops up with a dozen compiler errors. Here's the most common one:

Assets/Dissonance/Integrations/PureP2P/PureP2PServer.cs(4,7): error CS0246: The type or namespace name 'Byn' could not be found (are you missing a using directive or an assembly reference?)

This is true for both the "UNet High Level API (HLAPI)" & "PureP2P WebRTC Network".

I don't believe I'm missing anything from the tutorials found on the https://dissonance.readthedocs.io page.

Is there something obvious I'm missing?

I'm using Unity 2019.4.1f1, on MacOS.

Thanks in advance for any insight!

**Comment by YuliyF** [comment]
and.. what about :
```
using Byn.Awrtc;
using Byn.Awrtc.Unity;
```
The type or namespace name 'Byn' could not be found. How does it fix?

**Comment by martindevans** [comment]
Do you have the [WebRTC Video Chat](https://assetstore.unity.com/packages/tools/network/webrtc-video-chat-68030?aid=1100lJDF) package installed?

**Comment by YuliyF** [comment]
No, I have not. I bought a pack of audio chat and want to get it. I don't need a Video chat..

**Comment by martindevans** [comment]
Dissonance work by using the networking backend from other systems (or a custom networking system, it's up to you). To help with this we publish all the free "network integration packages" which send Dissonance traffic through other network services (e.g. [Mirror](https://assetstore.unity.com/packages/tools/integration/dissonance-for-mirror-networking-143290?aid=1100lJDF) or [Photon](https://assetstore.unity.com/packages/tools/integration/dissonance-for-photon-unity-networking-2-143288?aid=1100lJDF)).

The error you're getting here is because you've downloaded the integration package for Dissonance and [WebRTC Video Chat](https://assetstore.unity.com/packages/tools/network/webrtc-video-chat-68030?aid=1100lJDF) (Dissonance just uses the networking component of that asset, not the video chat part). So if you want to use that network backend you'd need to install that other asset too.

That's probably not what you want though! If your application is already using networking for other things, you should probably integrate Dissoance with that. If you aren't using any other networking systems yet we've got [a page on the documentation](https://placeholder-software.co.uk/dissonance/docs/Basics/Choosing-A-Network.html) which should help you choose which to use. There are plenty of free choices besides the expensive WebRTC integration!
