### ISSUE TITLE
Not switching audio device when I turn off my system Bluetooth before disconnecting wireless headset from the system.

### ISSUE THREAD

**Issue by Rohith-Nanthan** [Placeholder-Software/Dissonance#230]
![dissonance bug](https://user-images.githubusercontent.com/33635160/120803900-ac691700-c561-11eb-8c31-0e36e0c16c49.png)
## Context
If I switch off my system Bluetooth while my headset is still connected to the system, dissonance throws Unknown microphone capture error and it does not switch back to default microphone. It is also not switching my speaker to default system speaker. It works fine if I disconnect the headset first and then switch off the Bluetooth of my device.

## Expected Behavior
It must switch back to default speaker and microphone

## Actual Behavior
It throws error and I am unable to use speaker and microphone.
[Dissonance:Recording] (11:52:34.005) BasicMicrophoneCapture: Unknown microphone capture error (zero length clip) - restarting mic
UnityEngine.Debug:LogError (object)
Dissonance.Logs/LogMessage:Log () (at Assets/Plugins/Dissonance/Core/Log.cs:69)
Dissonance.Logs:SendLogMessage (string,Dissonance.LogLevel) (at Assets/Plugins/Dissonance/Core/Log.cs:98)
Dissonance.Log:WriteLog (Dissonance.LogLevel,string) (at Assets/Plugins/Dissonance/Core/Log.cs:181)
Dissonance.Log:Error (string) (at Assets/Plugins/Dissonance/Core/Log.cs:425)
Dissonance.Audio.Capture.BasicMicrophoneCapture:UpdateSubscribers () (at Assets/Plugins/Dissonance/Core/Audio/Capture/BasicMicrophoneCapture.cs:250)
Dissonance.Audio.Capture.CapturePipelineManager:Update (bool,single) (at Assets/Plugins/Dissonance/Core/Audio/Capture/CapturePipelineManager.cs:188)
Dissonance.DissonanceComms:Update () (at Assets/Plugins/Dissonance/Core/DissonanceCommsImpl.cs:683)

## Steps to Reproduce
_Provide a detailed set of steps to reproduce the problem_
1. Connect a wireless headset and start the communication
2. Turn off the system Bluetooth while the headset is still connected and being used.

## Your Environment

- **Dissonance version used**:  v8.0.0

- **Unity version**: 2020.3.6f1

- **Editor Operating System and version**: Microsoft Windows 10 Pro (x64)

- **Build Settings**: PC - Windows x86_64

**Comment by martindevans** [comment]
Could you check if the `OnAudioConfigurationChanged` callback ([docs](https://docs.unity3d.com/ScriptReference/AudioSettings.OnAudioConfigurationChanged.html)) happens when you do this? We've had some reports of it not happening in certain circumstances.

**Comment by Rohith-Nanthan** [comment]
Yes, it gets called every time I turn off the bluetooth but it throws an warning stating that Audio system failed to initialize.
![dissonance bug 2](https://user-images.githubusercontent.com/33635160/120888799-f4e30c00-c617-11eb-878e-3d7803d2d711.png)

**Comment by martindevans** [comment]
I think I'll need to have a look through the full log of this to see how Dissonance is reacting to the failed reset. Before sending me that could you please:

1. Add an event handler to that event which logs out `"Unity OnAudioConfigurationChanged called here (martindevans)"`
2. Raise Dissonance logging to `Debug` for all categories (Window > Dissonance > Diagnostic Settings)
3. Delete the current editor log
4. Repro the problem and send me the log

Thanks.

**Comment by Rohith-Nanthan** [comment]
[Dissonance debug.txt](https://github.com/Placeholder-Software/Dissonance/files/6602926/Dissonance.debug.txt)

**Comment by martindevans** [comment]
It looks like Dissonance is responding to the audio reset event basically as I would expect. The capture pipeline gets totally reset, which emptees out all buffers and attempts to re-initialise the microphone. You can see it re-initialising with messages like this:

> DEBUG [Dissonance:Recording] (17:06:08.478) BasicMicrophoneCapture: GetDeviceCaps name=`` min=`48000` max=`48000`

The empty `name` here indicates that Dissonance is not specifying a mic and is instead telling Unity to use whatever the system default Microphone is.

On the other end (playback) Dissonance actually doesn't have any input into which playback device is used - it simply plays audio through an AudioSource and Unity is responsible for playing that out through some actual hardware.

Unfortunately I think this is a Unity bug. If you report it to Unity please share a link to the bug report here.

Some potential workarounds:
 - Use NatDevice for the mic input. This is a microphone input asset that uses the system API directly instead of the Unity `Microphone` wrapper. It _might_ workaround the issue (but only for the mic).
 - [Force a reset](https://docs.unity3d.com/ScriptReference/AudioSettings.Reset.html) of the audio device in Unity a couple of seconds after the first one. This _might_ workaround the bug.

**Comment by martindevans** [comment]
Unfortunately I don't think there's much I can do about these bugs. Have you reported them to Unity to see if they know about the bugs or have a potential workaround?

For input device selection the bugs are coming up from the Unity `Microphone` API (e.g. `Failed to get recording driver capabilities` when calling [`Microphone.GetDeviceCaps`](https://docs.unity3d.com/ScriptReference/Microphone.GetDeviceCaps.html). Dissonance responds to this by disabling the input system (until a reset is forced). The only thing that can be done about this is simply to try again later and hope that the Unity API is no longer throwing exceptions.

For the output device issues Dissonance doesn't have any influence at all on the output device that Unity uses! The only thing I can can think that may be related is Unity not properly switching output device while there is an active audio playback (try playing some music through an audiosource instead of speech to see if the issue persists).
