### ISSUE TITLE
Lots of feedback when one or more people is inactive - not speaking

### ISSUE THREAD

**Issue by istvanContXtual** [Placeholder-Software/Dissonance#247]
Hi,

What are the recommended voice settings for oculus quest?

When we have more than 4-5 ppl  in the same room there is a very disturbing echo after a while. 
Usually it is caused by the user that is not speaking for a couple of minutes. As soon as the user speaks the feedback stops. 

We are using the latest Dissonance sdk, Unity 2020.3.25, and PUN dissonance integration. The target platform is Oculus Quest 2.

Thank you,
Istvan

**Comment by martindevans** [comment]
That sounds as if the `Automatic Gain Control` on the Quest microphone is "running away" when there's a long period of silence - automatically boosting the volume up and up until it causes feedback. Unfortunately I don't think you can directly control (i.e. turn off) the AGC on the Quest microphone, but there are a few possible ways to work around it:

The main defence against feedback is to turn on [Acoustic Echo Cancellation](https://placeholder-software.co.uk/dissonance/docs/Tutorials/Acoustic-Echo-Cancellation.html). Start with that.

Some other settings to tweak in [Voice Settings](https://placeholder-software.co.uk/dissonance/docs/Reference/Other/VoiceSettings.html):
 - Increase the amount of `Noise Suppression` (on a VR platform it's usually a good idea to have this set very high anyway, due to loud breathing noises etc).
 - Lower `Voice Detector Sensitivity`, this reduces the probability of classifying non-speech as speech.
 - Enable `Background Sound Removal`, this uses an ML model to detect background sounds and remove them. Note the `Noise Suppression` removes "noise" (e.g. fans) and will not distort speech, wheras this removes background sounds (e.g. dogs barking, heavy breathing) but will distort speech - it's often worth turning on especially in VR where breathing noise can be a problem, but don't maximise the intensity slider without testing it!
