### ISSUE TITLE
How can we test for different networks or...

### ISSUE THREAD

**Issue by hdev72** [Placeholder-Software/Dissonance#252]
Hello everyone
Dear admins, Do you have a sample game used dissonance for group voice chat? 
Before buying, we need to test the performance of dissonance, like handeling unstable networks, packet loss handeling, reconnection, big scale online users or another things.

It is better to make a sample game yourself or introduce a game that uses dissonance.

**Comment by hdev72** [comment]
thanks for your help.
pls see this images:
https://millo-l.github.io/static/017a91d3df72ed6117dcdb47fab3c810/21b4d/webrtc-server.png
Which architecture does dissonance use?
in case mcu and sfu we needs media server.

As I understand it, I have to prepare my own network server, apart from dissonance, and dissonance dont has any documentation to help run backend server (like Mirror/Photon/Webrtc), right?

**Comment by martindevans** [comment]
Dissonance does all of it's networking through whatever network system you choose (possibly a custom network, we have support for writing your own backend using our base classes to do most of the work). This _could_ be a separate voice server, but normally you don't need to do anything like that and instead you just setup so that it works through whatever network system you already have setup for your game/application.

> https://millo-l.github.io/static/017a91d3df72ed6117dcdb47fab3c810/21b4d/webrtc-server.png

Keep in mind that Dissonance does not use WebRTC networking topologies at all, so it's not _exactly_ any of those.

The closest is SFU - each Dissonance client sends an audio stream to the server which then forwards the audio on to other clients with no further processing. This is why Dissonance can scale to such large sessions - the server does not have to process every single audio stream.

In some network backends you can setup P2P routing between clients, in which case it can act a bit more like a mesh network (a server is still required, to act as a fallback if P2P connections cannot be made directly).
