### ISSUE TITLE
voice problem only some times, 80% of times is ok

### ISSUE THREAD

**Issue by hdev72** [Placeholder-Software/Dissonance#267]
Hello good time
I have a new problem, everything works fine, connect and exit of the server by a client works and the sound is exchanged well, but sometimes the sound is problematic, for example, I say hello, but on the other side (I only hear a tap, like hand tap on mic). The connection is established, the sound is heard, but there is no understanding at all, and this only fix with complete close app and open again

**Comment by martindevans** [comment]
If you're submitting an issue please make sure to fill in the issue template, it's there so I don't have to ask these same questions every time!

## Your Environment
- What version of Dissonance are you using? (Check Assets/Dissonance/changelog)
- What version of Unity are you using? (Check Help > About Unity)
- What editor Operating System and version?
- If you problem is happening in build, what platform is it built for?

**Comment by hdev72** [comment]
What version of Dissonance are you using? v8.2.1 (2022-07-23)
What version of Unity are you using? unity 2020.3.35f1, windows 10
What editor Operating System and version? Windows 10 Education Version 21H1  Os Build: 19043.1889
If you problem is happening in build, what platform is it built for? no problem in build

i found something can help, some times when i stop and start again client ( for switch between lobbies) packet loss getting more than 80% (showing on Dissonance Comms > Estimated Packet Loss) and when i stop and start again client that will be fix.

im using mirror with kcp transport,

**Comment by hdev72** [comment]
another sing can help, when problem happens i can hearing my voice from my speaker, not in other side

**Comment by hdev72** [comment]
Probably the +80% packet loss is because when the client is stopped, Dissonance still captures the voice and then when it is connected, it tries to send many packets , the solution may be that when the client is stopped, the microphone is also stop capturing??

**Comment by martindevans** [comment]
> EventQueue: Large number of received packets pending dispatch (12). Possibly due to network congestion (last frame was 3.9613ms) (only some times)

This error means that a lot of packets arrived all at once, but your frame rate is fine so it wasn't due to that. The problem is likely due to something in the network system causing congestion and a large number of packets arriving all at once.

Are you monitoring network statistics in Mirror to check if the network connection is fine overall?

**Comment by hdev72** [comment]
Do you monitor the network statistics in Mirror to check if the network connection is generally good?

Dear Martin, I don't know how to monitor the network statistics, but I think it doesn't matter when I lose a packet in the lan network, and I sometimes see this error,
I tested the connection on the local server and when I stop the client and start again, the packet loss drops to 50% on the network, you know the LAN has no problems with packet loss.

20% of the time when I stop and start the client I lose the packet, for example I do this behavior 5 times with no problem and the 6th time im getting packet loss near the 50%

**Comment by hdev72** [comment]
https://apphteam.com/packetLoss.png

**Comment by hdev72** [comment]
I think when the client stops, sending the packet it doesn't stop and I try to send a packet and when I reconnect to the client there is a lot of packet sending happening and packets are lost, something like a stack is going on.

**Comment by hdev72** [comment]
when client connect can i clear previus packets queued? a cleanup

**Comment by hdev72** [comment]
please watch this video:
https://apphteam.com/packetLossVideo.mp4

**Comment by martindevans** [comment]
> you know the LAN has no problems with packet loss.

That's (mostly) true for a wired LAN but it's definitely not true for wireless LAN!

Dissonance has a slightly different meaning when it talks about packet loss than what you expect. Audio is playing back at a fixed rate so if a packet is _delayed_ it can arrive late enough that the audio in that packet should have already been played - Dissonance counts this as a loss.

That is why I was asking about the `EventQueue: Large number of received packets pending dispatch (12). Possibly due to network congestion (last frame was 3.9613ms)` message - that means lots of packets were all delivered at once (due to some factor external to Dissonance) and that could cause them to count as "lost" packets.

> 20% of the time when I stop and start the client I lose the packet, for example I do this behavior 5 times with no problem and the 6th time im getting packet loss near the 50%

Unfortunately I couldn't hear any sound in your demo video, I assume when the packet loss number is high you cannot hear incoming voice?

> when client connect can i clear previus packets queued? a cleanup

I'm not sure what you mean, sorry.

**Comment by hdev72** [comment]
I tested with 8 users of my game and my voice was constantly cut and connected, or other people's voice was cut and connected for me.
These are the logs that occurred:

**Comment by hdev72** [comment]
>Dissonance has a slightly different meaning when it talks about packet loss than what you expect. Audio is playing back at a fixed rate so if a packet is delayed it can arrive late enough that the audio in that packet should have already been played - Dissonance counts this as a loss.

So as I understand if the network is delayed we will see packet loss and we won't be able to hear the delayed packets right?
Is there a setting so we can hear delayed packets?

>Unfortunately I couldn't hear any sound in your demo video, I assume when the packet loss number is high you cannot hear incoming voice?

yes

**Comment by hdev72** [comment]
here is my settings:
https://apphteam.com/myDissonanceSettings.png

**Comment by hdev72** [comment]
Due to the large number of users, low server cpu consumption is important to me. I don't know which one refers to the server cpu and which one refers to the user in settings help notes.

here is my settings:
https://apphteam.com/myDissonanceSettings.png

**Comment by hdev72** [comment]
today in local test i see bellow log when packet loss going to large number and cant hearing my voice in other side:

[Dissonance:Playback] (10:28:37.624) SpeechSession: Detected oversized buffer before playback started. Jitter:0.0247042ms (1) Buffered:240ms Expected:62ms. Discarding 178ms of audio...

**Comment by hdev72** [comment]
i think packets reciving success but dissonance discaridng part of audio, why? (Discarding 178ms of audio...)

**Comment by martindevans** [comment]
> These are the logs that occurred

All of these log messages are symptoms of the same problem - lots of packets are delivered together, causing many other problems. We really need to diagnose what is going wrong in Mirror to cause what is causing these huge delays.

As a workaround, can you try loading into the scene with the Dissonance `GameObject` _disabled_ and then enabling it after a short delay. If the problem is caused by something in your loading process that might work as a temporary workaround.

> Is there a setting so we can hear delayed packets?

No. Audio has to be played in order and packets which are dropped due to high delays are too late to be played because the point in time when they should have been played has already passed. Playing them later wouldn't make any sense (it would just sound like a jumbled mess).

> I don't know which one refers to the server cpu and which one refers to the client cpu in settings help notes. (Frame size and Audio quality)

 - `Audio Quality` - has no effect at all on server CPU usage. You're safe to raise that up unless your clients are _extremely_ CPU/bandwidth constrained.
 - `Frame Size` - A smaller frame size means more packets are sent per second, which increases server load. So `Large` frame sizes are the right choice for you.

> [Dissonance:Playback] (10:28:37.624) SpeechSession: Detected oversized buffer before playback started. Jitter:0.0247042ms (1) Buffered:240ms Expected:62ms. Discarding 178ms of audio...

When Dissonance is about to start playing some audio it delays it a little bit before starting playback (this is called jitter buffering), it chooses a buffer size (62ms in this case) and then each frame it checks if that much time has passed and then starts playback.

This error means that when it checked the buffer had 240ms of audio in it, even though there should only be 62ms. This is another symptom of the issue with large amounts of audio buffering up in the network and being delivered all at once.

> ... why? (Discarding 178ms of audio...)

There are two choices in this case when the buffer is grossly oversized: play back _all_ of the audio or throw some away. If all of the audio were played back then the playback would be 178ms behind where it should be, so the issue that caused over-buffering (usually just a transient issue) would cause a persistent lag. Latency is the most important aspect of VOIP quality, so keeping that large delay is a worse impact on quality than simply discarding the audio anf getting back into sync.

Remember that this _shouldn't ever happen_ - it's just a last-chance recovery system to attempt to cope with something going seriously wrong in the network! We should focus on trying to diagnose the problem with the networking rather than tweaking the recovery mechanism.

**Comment by hdev72** [comment]
Thank you for your helpful explanation, but I still haven't found the solution, I'm using kcp and want to try other things to transport, maybe it will solve the problem, do you have any suggestions for transport?

When I tested it today, I had nothing to do with stop/start the client, and in the normal process, I had a problem and 30% of the time I did not receive the sound and I faced the following log:
SpeechSession: Detected oversized buffer before playback started. Jitter:0.0247042ms (1) Buffered:240ms Expected:62ms. Discarding 178ms of audio...

**Comment by hdev72** [comment]
>All of these log messages are symptoms of the same problem - lots of packets are delivered together, causing many other problems. We really need to diagnose what is going wrong in Mirror to cause what is causing these huge delays.

i think kcp (udp reliable) working like tcp protocol and that's the problem for delays

**Comment by hdev72** [comment]
I think that as it is in your demo, your suggested transport is telepathy and my mistake is that I have changed it to kcp.
Is Telepathy udp? Because you already told me that tcp is not suitable for voice chat

**Comment by hdev72** [comment]
I think there is a problem, when I talk to the phone I immediately see the error in the log editor, it shows that it is not received with a delay, but the delay is detected (dissonance logs are printed).

**Comment by hdev72** [comment]
another test, locale and without wireless with two unity project in editor:
i hosted with a editor and joined with another editor in same pc, everything at start is ok and after i stop and start a client facing with packet loss and bellow log:
SpeechSession: Detected oversized buffer before playback started. Jitter:0.008891091ms (1) Buffered:240ms Expected:60ms. Discarding 180ms of audio...

And this packet loss was never resolved

It seems that if the user's network is interrupted or delayed once, it will always fall behind in time and will not receive any more packets.

**Comment by martindevans** [comment]
> SpeechSession: Detected oversized buffer before playback started

When you receive these errors do you always/usually also get the error `EventQueue: Large number of received packets pending dispatch` around the same time (probably just before)?

> I'm using kcp (mirror) and want to try other things to transport, maybe it will solve the problem, do you have any suggestions for transport?

Any Mirror transport that supports _Unreliable_ packets should be fine. e.g. `Ignorance`, `LiteNetLib`, `Steam`, `KCP`, `Mirror WebRTC`. I know a lot of people have used `Ignorance` successfully before.

> SimpleWebTransport

SimpleWebTransport only supports `Reliable` packets, this isn't really suitable for voice chat (it'll work better in ok conditions, but will make very bad conditions much worse due to the delays incurred due to reliability).

**Comment by hdev72** [comment]
> a lot of people have used Ignorance successfully before.

you say used for dissonance successfully or generally?

**Comment by martindevans** [comment]
It's been used successfully with Dissonance for a long time (back when we first release Mirror support we actually _required_ Ignorance).

**Comment by hdev72** [comment]
i tested ignorance too but again getting packet loss, It seems that the high speed (unreliable) makes dissonance unable to handle the high number of received packets. Please check and solve this issue for the next updates, for me only simpleWebTransport works fine.

**Comment by hdev72** [comment]
Please completely delete this issue.
I had asked misleading questions that confuse users.
