### ISSUE TITLE
Error: configured 'unreliable' channel is out of range!

### ISSUE THREAD

**Issue by wilg** [Placeholder-Software/Dissonance#34]
The documentation doesn't appear to contain any information on how to properly configure these channels.

```
DissonanceException: [Dissonance:Network] HlapiCommsNetwork: Error: configured 'unreliable' channel is out of range! This is likely caused by "set the wrong channel number in the HLAPI Comms Network component", see the documentation at "https://dissonance.readthedocs.io/en/latest/Basics/Quick-Start-UNet-HLAPI/" or visit the community at "http://placeholder-software.co.uk/dissonance/community" to get help. Error ID: B19B4916-8709-490B-8152-A646CCAD788E
Dissonance.Integrations.UNet_HLAPI.HlapiCommsNetwork.Initialize () (at Assets/Dissonance/Integrations/UNet_HLAPI/HlapiCommsNetwork.cs:59)
Dissonance.Networking.BaseCommsNetwork`3[Dissonance.Integrations.UNet_HLAPI.HlapiServer,Dissonance.Integrations.UNet_HLAPI.HlapiClient,Dissonance.Integrations.UNet_HLAPI.HlapiConn].Initialize (System.String playerName, Dissonance.Rooms rooms, Dissonance.PlayerChannels playerChannels, Dissonance.RoomChannels roomChannels, System.Action`1 connectionCallback) (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:243)
Dissonance.DissonanceComms.Start () (at Assets/Plugins/Dissonance/DissonanceComms.cs:352)
```

**Comment by martindevans** [comment]
You're quite right, it should have a bit in `Step 1a: Setup Network Manager` - sorry about that.

Below is an image of the inspector for the Dissonance HLAPI network inspector (left) and the Network Manager inspector (right). This has been set up so that the two channels in Dissonance (reliable and unreliable) correspond to the same channel numbers on the network manager (reliable => reliable sequenced and unreliable => unreliable):

![untitled](https://cloud.githubusercontent.com/assets/177519/26585426/fcad7f0a-4543-11e7-944e-255487457d5b.png)

The default setup for both of these components should work out of the box. They should have:

 - Reliable == Channel #0 (Reliable sequenced)
 - Unreliable == Channel #1 (Unreliable)

Did you change any of these settings? Or were the default settings somehow broken?

**Comment by martindevans** [comment]
I've now added this section to the documentation, you can find it [here](https://dissonance.readthedocs.io/en/latest/Basics/Quick-Start-UNet-HLAPI/#step-1a-setup-network-manager).

**Comment by wilg** [comment]
I had the default settings so I guess it MUST be set to advanced? I haven't had a chance yet to test again but I did confirm advanced was unchecked.

**Comment by martindevans** [comment]
When you clicked advanced what were the default settings? Whenever I've tested this in the past they've been correct by default (0 reliable sequenced, 1 unreliable).

**Comment by wilg** [comment]
The default settings were exactly that, which is what's weird. I'll let you know if I figure out anything more.

**Comment by wilg** [comment]
It worked when I manually set it to advanced and entered those channel settings, but not on auto.

**Comment by martindevans** [comment]
The docs now require that you check the channel configuration (i.e. toggle on advanced), so what you're doing is now the expected way to do things.

Looking at the [HLAPI source code](https://bitbucket.org/Unity-Technologies/networking/src/78ca8544bbf4e87c310ce2a9a3fc33cdad2f9bb1/Editor/NetworkManagerEditor.cs?at=5.3&fileviewer=file-view-default#NetworkManagerEditor.cs-215) it becomes clear why this is. The line I have highlighted there is what happens when you toggle on advanced config - this does not just toggle on part of the UI it makes a permanent change to the network manager! If you toggle it back off again it doesn't appear to undo those changes. So the real requirement apwars to be that you have toggled this setting on at least once.

Not the best UI design I've ever seen!

**Comment by wilg** [comment]
🤦‍♂️
