### ISSUE TITLE
[feature] Support for Nakama server

### ISSUE THREAD

**Issue by rodgalvao** [Placeholder-Software/Dissonance#37]
Please add support for Nakama.

It is an interesting distributed open source networking server:

https://heroiclabs.com/
https://www.assetstore.unity3d.com/en/#!/content/81338

**Comment by martindevans** [comment]
Nakama isn't one I've seen before - looks pretty interesting. I've found a [feature request on Nakama](https://github.com/Placeholder-Software/Dissonance/issues/37) to add voice chat so I'm going to ask some questions there to ascertain if it's possible.

**Comment by fingerx** [comment]
@martindevans  any news? thanks

**Comment by martindevans** [comment]
I contacted the Nakama guys asking about this. Currently Nakama is built on top of TCP connections which means it can only send reliable/in-order packets. This is a problem because that introduces a lot of unnecessary latency jitter and really compromises the voice quality. [Novabyte said](https://github.com/heroiclabs/nakama/issues/82#issuecomment-312437105) that they're going to be transitioning to a UDP based transport layer which would be perfect for Dissonance. So we're really waiting on that to be implemented before we can get started on this.

**Comment by alexpareto** [comment]
Now that Nakama supports UDP, will Dissonance be adding support? Thanks!

**Comment by martindevans** [comment]
We're definitely planning to look into Nakama support soon, it will _probably_ be the next network integration we do.

**Comment by omerfaruk** [comment]
are there still no integration ?

**Comment by martindevans** [comment]
Not yet - it's never quite made it's way to the top of the list! Sorry about that. I will try to make time to look into it soon.

In the meantime don't forget that anyone can write a network integration for Dissonance - in terms of coding it's not too complex, check out the [guide for that](https://dissonance.readthedocs.io/en/latest/Tutorials/Custom-Networking/). It only takes me a long time because I have to be prepared to support new users of Dissonance with the underlying network system (and a new set of problems that can cause).

**Comment by martindevans** [comment]
A quick update on this: I had a chat to one of the Nakama devs the other day. We both think Dissonance could be a really good fit for Nakama but it might be a little more complex than your average network integration. We're going to reconvene in the new year to work out how to fit the two together.

**Comment by marcofaggian** [comment]
Any news? Looking forward to that backend!

**Comment by martindevans** [comment]
We haven't got together yet to follow up on our Discussion from last time, hopefully that will be soon. @novabyte any updates from your end?

**Comment by martindevans** [comment]
Realistically I don't think this is going to happen, sorry everyone :(

As I said above this would be a very complicated integration, probably requiring breaking changes to Dissonance to fit into how Nakama does things at scale (e.g. we can't list all players in your session with `DissonanceComms.Players` if the session is nominally thousands of players). Unfortunately there's not enough demand to justify such a large amount of work.

If anyone really wants this integration contact me (martin@placeholder-software.co.uk) about sponsoring development of it and we'll see what we can work out. We've been hired to integrate Dissonance with MMOs before, so I'm confident this is at least possible!
