### ISSUE TITLE
[feature] Tizen support

### ISSUE THREAD

**Issue by Asaadmk** [Placeholder-Software/Dissonance#42]
currently getting this when building for tizen

The name `Microphone' does not exist in the current context

**Comment by martindevans** [comment]
Hi Asaadmk,

The `Microphone` class is part of Unity, if that's missing it's most likely because Unity itself does not support microphones on tizen.  I can't find any specific mention of Microphones not working on Tizen in the documentation. However there is [this post in the forums](https://forum.unity3d.com/threads/tizen-microphone-support.427190/#post-2761080) by a Unity staff member who specifically says they don't work. You may need to contact Unity (perhaps bump that thread) to see if this still applies in the latest version of Unity.

If the Unity microphone class does not exist on Tizen you're not totally out of options. You could build a new microphone class which calls directly into the platform native microphone API and then passes that data across to Dissonance. We don't officially support Tizen but I'll be happy to provide some advice on how to do that if that's what you decide to do.

I'll close this as "Won't fix" for now since we don't plan on adding Tizen support. Feel free to post here again or to open a new issue if you need any more help :)
