### ISSUE TITLE
[bug] High CPU use LLAPI dedicated server on Windows 2012

### ISSUE THREAD

**Issue by awonnink** [Placeholder-Software/Dissonance#49]
## Context
  Using Unity 2017.1.f3, to create server 'game' running on Windows server 2012. Dissonance 3.0.0, LLApi

## Expected Behavior
Generally low CPU usage

## Actual Behavior
CPU use starts at 40% and sometimes rises to 90% or more so other processes are suppressed (like RDP). Only a very few clients are connected.

## Workaround
Not yet found

## Fix
Not yet found

## Steps to Reproduce
1. Use LLApi
2. Drag the DissonanceDemoSetup in an empty scene
3. Attach a script to this gameobject with in the Start() 
	void Start () {
        var dissonanceNetwork = GetComponent<UNetCommsNetwork>();
        dissonanceNetwork.InitializeAsDedicatedServer();
    }
4. Create game with this scene
5. Let it run on Windows 2012 server while looking at Taskmanager: immediately the CPU use rises to about 40%

## Your Environment
- Unity 2017.1.f3, Virtual Windows server 2012 R2 Standard, 2.39 GHz, 4 GB. Dissonance 3.0.0
-  Microsoft Windows 10 Pro 10.0.10586 (x64) 
- **Build Settings**: x86_64
- No Unity installed on server
![dissonance_server_issue](https://user-images.githubusercontent.com/8362626/29859045-938467fe-8d60-11e7-9368-2eb776021e7b.png)
![dissonance server issue2](https://user-images.githubusercontent.com/8362626/29859054-9f573cc8-8d60-11e7-8aca-af53147a3ea0.png)

**Comment by martindevans** [comment]
I just tried to reproduce this using the Dissonance LLAPI demo scene. I don't have a windows server 2012 box so I used by development PC - Ryzen 1700X with windows 10 Professional.

I hosted a dedicated server (when idle it hovers around 1% CPU usage) and connected six clients (again all hovering around 1% CPU usage, even when someone is speaking). There was absolutely no visible change in CPU usage as I connected more clients or as clients started speaking. Could you test the demo scene on your server to see if the problem is only in your app?

![untitled](https://user-images.githubusercontent.com/177519/29875207-1ef5fc5a-8d91-11e7-917f-346b2ae2f475.png)

**Comment by awonnink** [comment]
Tried the demo scene but with similar results. But then I tried an empty scene on 2012 server (normally we don't have Unity stuff on this server), and this also resulted in a very high CPU. 
So it really hasn't to do with Dissonance, it is something with Unity and 2012 server. 
(I had also noticed that on my development Win 10 PC the server worked fine)
Sorry to have bothered you!

**Comment by martindevans** [comment]
Thanks for trying that out. Good luck tracking down the issue!
