### ISSUE TITLE
[help] Disconnect after 5-10 minutes. Error ID: 6DB702AA-D683-47AA-9544-BE4857EF8160

### ISSUE THREAD

**Issue by donnytrona** [Placeholder-Software/Dissonance#54]
## Context
After joining the server voice chat works perfectly fine, but after 5 - 10 minutes the clients get timed out.

## Your Environment
_Include as many relevant details about the environment you experienced the bug in_

- **Dissonance version used**: 2.0.0

- **Unity version**: 5.6.2f1

- **Editor Operating System and version**: Windows 8.1 Pro

- **Build Settings**: Windows, x86_64

- **ErrorLogs**: 
[error.log](https://github.com/Placeholder-Software/Dissonance/files/1327973/error.log)
[output_log.txt](https://github.com/Placeholder-Software/Dissonance/files/1327974/output_log.txt)

**Comment by martindevans** [comment]
Hi donnytrona,

Could I get you to upgrade to the latest version of Dissonance ([3.0.2](https://placeholder-software.co.uk/dissonance/releases/3.0.2.html)) - a large part of the work in Dissonance 3.0.0 was a complete overhaul of the networking system so there's a chance this issue has already been fixed by that version.

If you still have the problem after upgrading could you give me a few more details on the problem:
 - Which network integration are you using?
 - How many players do you have in the session?
 - Does this bug affect multiple players in the session at the same time?
 - Does this same bug happen in the demo scene for the network integration you are using?

**Comment by donnytrona** [comment]
Thanks upgrading seems to have fixed the issue.

**Comment by martindevans** [comment]
Excellent!
