### ISSUE TITLE
Dissonance 0.0.2 Unet_HLAPI Exception

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#6]
1. Create a new project in Unity 5.4.2p2 and import Dissonance 0.0.2 package

2. Open the Unet_HLAPI demo scene

3. Notice in the NetworkManager there are no spawnable prefab (HlApiPlayerTracker should be there?)

4. Start the scene and notice the Exception

![dissonance-0 0 2](https://cloud.githubusercontent.com/assets/6678654/19914840/f6573312-a0e8-11e6-85cd-27312fb59cf4.PNG)

Thanks :)

**Comment by martindevans** [comment]
I actually found this bug myself yesterday (and fixed it, of course). I'll be releasing Dissonance 0.0.3 later today which will include that fix. Thanks for the report :)

> there are no spawnable prefab (HlApiPlayerTracker should be there?)

As far as I understand it this isn't actually *required* - registering the prefab just loads it into memory when the scene is loaded to ensure there's no loading delay when the prefab is instantiated. This isn't done for the HlapiPlayerTracker because it's such a tiny prefab (requires no assets, one behaviour).
