### ISSUE TITLE
[feature] Create new rooms during runtime

### ISSUE THREAD

**Issue by jakemoves** [Placeholder-Software/Dissonance#66]
Is it currently possible to define / create new rooms during runtime? If so, how? If not... it would be very useful, but maybe it's not architecturally possible.

**Comment by martindevans** [comment]
There's two ways to create a new room at runtime.

The best way of doing it (because it presents a better interface) is to directly use the [Channel API](https://dissonance.readthedocs.io/en/latest/Tutorials/Script-Controlled-Speech/) to open and close audio channels. This is how the trigger components work internally.

```
DissonanceComms comms;

// Begin listening to a room
var listen = comms.Rooms.Join("Some Room Name");

// Begin talking to a room
var transmit = comms.RoomChannels.Open("Some Room Name");

// Stop listening
comms.Rooms.Leave(listen);

// Stop talking
comms.RoomChannels.Close(transmit);
```

You could also create a new pair of [VoiceBroadcastTrigger](https://dissonance.readthedocs.io/en/latest/Reference/Components/Voice-Broadcast-Trigger/)/[VoiceReceiptTrigger](https://dissonance.readthedocs.io/en/latest/Reference/Components/Voice-Receipt-Trigger/) components and configure them as you like. For example:

```
var c = SomeGameObject.AddComponent<VoiceBroadcastTrigger>();
c.RoomName = "Some Room Name";
c.ChannelType = CommTriggerTarget.Room;
```

I'll close this issue since I've answered the question, but feel free to ask followup questions if it's not clear :)

**Comment by jakemoves** [comment]
Thank you for the speedy reply!

Would you expect either of these to work with text chat messages directed at a particular Room?

**Comment by martindevans** [comment]
In my first reply I linked you to a general tutorial on "Script controlled speech". There's a more specific "Channel API" tutorial [here](https://dissonance.readthedocs.io/en/latest/Tutorials/Directly-Using-Channels/)
