### ISSUE TITLE
0.0.3 Unet demo scene Exception

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#7]
Hi,

Just updated to 0.0.3 and get an Exception shortly after client join, then Dissonance stops working after that (no voice transmission).

1. Import Dissonance 0.0.3 in fresh 5.4.2p2 Unity project.

2. Remove Playmaker, Forge Networking and Photon integration.

3. Open DissonanceHlapiDemo scene

4. Set Playback Prefab in Dissonance scene object.

5. Build an standalone executable

6. Run server in Unity and make the standalone executable join (both are on localhost).

7. Get the following Exception

![dissonance](https://cloud.githubusercontent.com/assets/6678654/19999287/591f04ec-a2ac-11e6-96f7-f63d19031ce3.jpg)

Any idea? :)

**Comment by martindevans** [comment]
I'm looking in to this. One thing I wanted to note though is that all the trace stuff shouldn't be turned on (it's probably my mistake that I left it on by default before building 0.0.3) - if trace is on for playback the audio system will stutter because all the trace logging takes too much time! To change this go to your DissonanceComms inspector, click the diagnostic settings button and change the level to something more sensible like Info.

**Comment by martindevans** [comment]
I can't reproduce this, but I'm pretty confident I know what the problem is. Can you confirm that `_resampler` is null when `_resampler.Reset();` is called (EncoderPipeline:76).

**Comment by citron4000** [comment]
Thanks Martin, I will be able to try this fix in 36 hours and let you know.

For the trace you are right, it is turned on in the prefabs in 0.0.3 and make things really slow.

**Comment by martindevans** [comment]
I'm going to go ahead and ship out 0.0.4 right now (at the very least I have fixed the logging problem). I have included my suggested fix in 0.0.4 so simply testing that should be able to confirm if your problem is fixed :)

**Comment by citron4000** [comment]
The problem is fixed in 0.0.4. I will test further this week. Thanks!
