### ISSUE TITLE
Change Input Device

### ISSUE THREAD

**Issue by martindevans** [Placeholder-Software/Dissonance#74]
As [reported by KamiKaze425](https://forum.unity.com/threads/released-dissonance-unity-voice-chat.438271/page-3#post-3368740) changing the Microphone input device has no affect on Unity 2017.2 (and higher?).

Unity issue tracker: https://issuetracker.unity3d.com/issues/microphone-dot-start-is-not-recording-the-audio-from-selected-recording-device

**Comment by SniperED007** [comment]
Hi, 
I'm the guy who logged the bug with Unity, just an update from them that I received via e-mail... they said it will be fixed in the Unity 2018.1 release.

**Comment by martindevans** [comment]
Thanks for the update. I hope this doesn't mean they're *not* going to backport the fix to 2017.2/3 though :/

**Comment by SniperED007** [comment]
I had asked them too, but they said they would let me know later that day if they do decide to... and I haven't heard back since (that was about 2 weeks ago). I'm also waiting on this bug that is going to be fixed as part of 2018.1 -> https://issuetracker.unity3d.com/issues/unity-microphone-does-not-work-with-razer-kraken-7-dot-1-chroma-headsets-while-razer-synapse-is-installed

**Comment by martindevans** [comment]
Going by that second issue you linked which is marked as "Fixed in future release" I would guess that they don't plan to backport this kind of fix :(

**Comment by martindevans** [comment]
Unity has marked the issue as "resolved in 2018.2". This is disappointing because it means this will continue to be an issue in 2017.2, 2017.3 and 2018.1 forever :(

However I can't do anything about the Unity bugfixing process and it looks like this is the best resolution we're going to get so I shall reluctantly close this issue.

**Comment by SniperED007** [comment]
it was resolved in 2018.1 which was released today.
