### ISSUE TITLE
[bug] Encoded audio heap is getting very large

### ISSUE THREAD

**Issue by ibrahimpenekli** [Placeholder-Software/Dissonance#78]
We use the plugin voice streaming between a Hololens and PC. Sometimes PC application (also UWP app) freezes. Here is the log:

[Dissonance:Playback] EncodedAudioBuffer: Error: Encoded audio heap is getting very large (41 items)! This is probably a bug in Dissonance, we're sorry! Please report the bug on the issue tracker "https://github.com/Placeholder-Software/Dissonance/issues". You could also seek help on the community at "http://placeholder-software.co.uk/dissonance/community" to get help for a temporary workaround. Error ID: 59EE0102-FF75-467A-A50D-00BF670E9B8C

Dissonance version 6.0.2
Unity 2017.2.0f3
Windows 10 Pro 1709
UWP x86 and x64

**Comment by martindevans** [comment]
Hi,

I think that the message you're getting here is caused by the freeze, not the other way around. This message simply indicates that the playback system has received a lot of audio which it has not played back yet, if the application is freezing for some other reason this will cause playback to fall behind (because it's not playing audio during the freeze). Could the freeze be caused by something else?

I would suggest running the application with the Unity profiler attached and seeing if there is any obvious cause of the freeze.

**Comment by ibrahimpenekli** [comment]
Hi @martindevans ,

I agree with your thoughts. I'm trying to find actual cause.
Thanks!
